### ISSUE TITLE
loadDatabase.js fails to connect to local MongoDB instance

### ISSUE THREAD

**Issue by ItalianJack** [btdobbs/WA#4]
After setting up MongoDB and updating completed project 5 to include project 6 data and configurations, `loadDatabase.js` fails to establish a connection to the locally running MongoDB instance; it tries using IPv6. This was fixed by changing `localhost` to `127.0.0.1:27017` in line 24 of `loadDatabase.js`.

**Comment by btdobbs** [comment]
Thanks for the comment.  Did you get the latest version of loadDatabase.js?   I updated the URI to "mongodb://127.0.0.1/project6" early this morning.  I am curious to know if this works without the default port of 27017.

**Comment by ItalianJack** [comment]
Yes, it works without the port number specified.

**Comment by btdobbs** [comment]
Excellent, thanks for confirming.
