### ISSUE TITLE
Project 6 - Loopback IP address needs to be specified in webServer.js

### ISSUE THREAD

**Issue by ItalianJack** [btdobbs/WA#5]
Similarly to issue [https://github.com/btdobbs/WA/issues/4](https://github.com/btdobbs/WA/issues/4), line 49 of webServer.js needs to have the URL changed from `localhost` to `127.0.0.1`. It appears that port specification is unnecessary

**Comment by btdobbs** [comment]
Thanks for the note.  Per our class discussion today, please update your repository with the latest changes.  You are probably working from a file downloaded earlier in the semester.  Both webServer.js and loadDatabase.js were updated around 2am this morning with the 127.0.0.1 URI.
